name: Releases
on:
  push:
    tags:
      - "*"
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: ncipollo/release-action@v1
        with:
          generateReleaseNotes: true
          skipIfReleaseExists: true
