name: "Reviewdog"
on:
  pull_request:
    branches: ["main"]
permissions:
  contents: read
  pull-requests: write
jobs:
  detect-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
      - name: Run detect-secrets
        uses: reviewdog/action-detect-secrets@3bc07a8ce36864e49536f7dba77f7c69ff5219a3
        with:
          reporter: "github-pr-review"
  golangci-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
        with:
          fetch-depth: 0
      - name: golangci-lint
        uses: reviewdog/action-golangci-lint@c76cceaaab89abe74e649d2e34c6c9adc26662d2
        with:
          reporter: "github-pr-review"
