name: Auto Tagging
on:
  push:
    branches:
      - main
    paths:
      - "VERSION"
jobs:
  version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get_version.outputs.version }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Get Version
        id: get_version
        run: |
          if [ -f VERSION ]; then
            version=$(cat VERSION)
          else
            echo "VERSION file not found, using default version 0.0.0"
            version="0.0.0"
          fi
          echo "VERSION=${version}" >> "$GITHUB_OUTPUT"
      - name: Debug Version
        run: echo "VERSION=${{ steps.get_version.outputs.version }}"
  tag:
    runs-on: ubuntu-latest
    needs: version
    if: needs.version.outputs.version != '0.0.0'
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Push tag
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag_prefix: "v"
          custom_tag: ${{ needs.version.outputs.version }}
name: Auto Tagging
on:
  push:
    branches:
      - main
    paths:
      - "VERSION"
jobs:
  version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get_version.outputs.version }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Get Version
        id: get_version
        run: |
          if [ -f VERSION ]; then
            version=$(cat VERSION)
          else
            echo "VERSION file not found, using default version 0.0.0"
            version="0.0.0"
          fi
          echo "VERSION=${version}" >> "$GITHUB_OUTPUT"
      - name: Debug Version
        run: echo "VERSION=${{ steps.get_version.outputs.version }}"
  tag:
    runs-on: ubuntu-latest
    needs: version
    if: needs.version.outputs.version != '0.0.0'
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Push tag
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag_prefix: "v"
          custom_tag: ${{ needs.version.outputs.version }}
