name: Test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
permissions:
  contents: read
jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      - name: Set up Go
        uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c
        with:
          go-version: "1.25"
      - name: Test
        run: go run gotest.tools/gotestsum@latest --jsonfile go-test.json --format
          testname
      - name: Test Summary
        uses: dorny/test-reporter@3d76b34a4535afbd0600d347b09a6ee5deb3ed7f
        if: ${{ !cancelled() }}
        with:
          name: test-results
          path: go-test.json
          reporter: "golang-json"
