name: Test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.25"
      - name: Test
        run: go run gotest.tools/gotestsum@latest --jsonfile go-test.json --format testname
      - name: Test Summary
        uses: dorny/test-reporter@v2
        if: ${{ !cancelled() }}
        with:
          name: test-results
          path: go-test.json
          reporter: "golang-json"
