name: Test
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v5

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24'

    - name: Test
      run: go run gotest.tools/gotestsum@latest --junitfile unit-tests.xml --format pkgname
    
    - name: Test Summary
      uses: test-summary/action@v2.3
      with:
        paths: "unit-tests.xml"
        output: test-summary.md
        show: "all"
      if: always()